//
// Created by seedsone on 18-9-12.
//

#ifndef SERVERFLY_HTTP_DEFINE_HPP
#define SERVERFLY_HTTP_DEFINE_HPP

#define HTTP_HEADER_LENGTH 12
#define HTTP_HEADER_ALLOW 0
#define HTTP_HEADER_CONTENT_ENCODING 1
#define HTTP_HEADER_CONTENT_LENGTH 2
#define HTTP_HEADER_CONTENT_TYPE 3
#define HTTP_HEADER_DATE 4
#define HTTP_HEADER_EXPIRES 5
#define HTTP_HEADER_LAST_MODIFIED 6
#define HTTP_HEADER_LOCATION 7
#define HTTP_HEADER_REFRESH 8
#define HTTP_HEADER_SERVER 9
#define HTTP_HEADER_SET_COOKIE 10
#define HTTP_HEADER_WWW_AUTHENTICATE 11

#endif //SERVERFLY_HTTP_DEFINE_HPP
